### ISSUE TITLE
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by ljcucc** [powerbot15/image-compressor#3]
I got this error when I compressing my image

```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at ImageCompressor.grayScale (file:///D:/Project/node_modules/image-compressor/image-compressor.js:164:40)
    at ImageCompressor.imageFilters (file:///D:/Project/node_modules/image-compressor/image-compressor.js:212:22)
    at ImageCompressor.compressAddOn (file:///D:/Project/node_modules/image-compressor/image-compressor.js:74:18)
    at ImageCompressor.compress (file:///D:/Project/node_modules/image-compressor/image-compressor.js:59:18)
    at ImageCompressor.imageLoaded (file:///D:/Project/node_modules/image-compressor/image-compressor.js:34:18)
```

with this:

```
   var imageCompressor = new ImageCompressor();
    
    var compressorSettings = {
            toWidth : 100,
            toHeight : 100,
            mimeType : 'image/jpg',
            mode : 'strict',
            quality : 0.6,
            grayScale : true,
            sepia : true,
            threshold : 127,
            vReverse : true,
            hReverse : true,
            speed : 'high'
        };
    
    window.addEventListener("load",e=>{
        imageCompressor.run("test.jpg", compressorSettings, proceedCompressedImage);
    })
    
    
    function proceedCompressedImage (compressedSrc) {
        console.log(compressedSrc)
    }
```
what is this happend? **X(**

**Comment by powerbot15** [comment]
Due to a CORS policy https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS browser blocks access to images which are not on the same domain as a web-page. In your case I think you need to launch some simple web-server locally(not just run HTML file) and then you can have access to local files from your computer
